"""
Vendor the public SSL-AASIST implementation with its fairseq dependency removed.

`public_ckpt/ssl_aasist/model_hf.py` (from ash56/ssl-aasist, itself Tak et al.'s
SSL-AASIST) builds its XLS-R front-end through fairseq, which will not
co-install against this repo's pinned torch 2.13 / torchaudio 2.11. We keep the
AASIST back-end *verbatim* -- it is pure PyTorch -- and swap only the front-end
for `torchaudio.pipelines.WAV2VEC2_XLSR_300M`, whose weights are loaded from the
public checkpoint via torchaudio's own authoritative fairseq key mapping
(`torchaudio.models.wav2vec2.utils.import_fairseq._convert_state_dict`).

The surgery is done textually and every substitution is asserted, so this is
reproducible and reviewable rather than a hand-retyped 605-line file. Any
upstream edit that moves an anchor makes this script fail loudly instead of
silently vendoring something different.

    python vendor_aasist.py     # writes aasist_backend.py
"""

import os

SRC = "public_ckpt/ssl_aasist/model_hf.py"
DST = "aasist_backend.py"

NEW_HEADER = '''"""
AUTO-GENERATED by vendor_aasist.py -- do not edit by hand.

AASIST back-end (Jung et al., ICASSP 2022) + SSL-AASIST wrapper (Tak et al.),
taken verbatim from ash56/ssl-aasist `model_hf.py` except that the fairseq
XLS-R front-end is replaced by torchaudio's WAV2VEC2_XLSR_300M.
"""
import random
from typing import Union
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor
import torchaudio
from torchaudio.models.wav2vec2.utils.import_fairseq import _convert_state_dict

___author__ = "Hemlata Tak"
__email__ = "tak@eurecom.fr"

############################
## FOR fine-tuned SSL MODEL
############################

'''

# fairseq's `model(x, mask=False, features_only=True)['x']` is the final
# transformer-encoder output. torchaudio's Wav2Vec2Model.forward returns exactly
# that as its first element (feature extractor -> feature projection ->
# transformer, with the trailing layer_norm that XLS-R's layer_norm_first=True
# config implies). Shapes and semantics therefore match (B, T, 1024).
NEW_SSLMODEL = '''class SSLModel(nn.Module):
    """XLS-R 300M front-end backed by torchaudio instead of fairseq.

    `extract_feat` returns the final transformer-encoder output (B, T, 1024),
    matching fairseq's `features_only=True` -> ['x'].
    """

    def __init__(self, device=None):
        super(SSLModel, self).__init__()
        self.model = torchaudio.pipelines.WAV2VEC2_XLSR_300M.get_model()
        self.out_dim = 1024

    def load_fairseq_weights(self, ssl_state_dict):
        """Load fairseq-format XLS-R weights (keys already stripped of any
        `ssl_model.model.` prefix). Strict: every tensor must land."""
        conv = {"model." + k: v for k, v in _convert_state_dict(ssl_state_dict).items()}
        self.model.load_state_dict(conv, strict=True)
        return len(conv)

    def extract_feat(self, input_data):
        if input_data.ndim == 3:
            input_tmp = input_data[:, :, 0]
        else:
            input_tmp = input_data
        emb, _ = self.model(input_tmp)
        return emb


'''


def main():
    if not os.path.exists(SRC):
        raise SystemExit(f"missing {SRC} -- download the checkpoint repo first")
    src = open(SRC).read()

    # 1. header / imports -----------------------------------------------------
    anchor = "#---------AASIST back-end------------------------#"
    assert anchor in src, "AASIST back-end anchor not found -- upstream file changed"
    head, tail = src.split(anchor, 1)
    out = NEW_HEADER + NEW_SSLMODEL + anchor + tail

    # 2. drop the transformers base class ------------------------------------
    subs = [
        ("class Model(PreTrainedModel,nn.Module):", "class Model(nn.Module):"),
        ("    config_class = SSLConfig\n", ""),
        ("    def __init__(self,config):\n        super().__init__(config)",
         "    def __init__(self, config=None):\n        super().__init__()"),
    ]
    for old, new in subs:
        assert old in out, f"anchor not found, upstream file changed: {old!r}"
        out = out.replace(old, new, 1)

    # 3. expose the 160-d readout alongside the logits ------------------------
    # our TTA harness calls model(wav) -> (logits, emb)
    old_ret = "        output = self.out_layer(last_hidden)\n        \n        return output"
    assert old_ret in out, "forward() return anchor not found"
    out = out.replace(old_ret,
                      "        output = self.out_layer(last_hidden)\n"
                      "        \n"
                      "        return output, last_hidden", 1)

    # 4. nothing fairseq/transformers may survive -----------------------------
    # NB: `torchaudio.models.wav2vec2.utils.import_fairseq` is torchaudio's own
    # key-mapping helper and does NOT require fairseq to be installed -- it is
    # the one permitted occurrence of the substring.
    for banned in ("import fairseq", "fairseq.checkpoint_utils", "PreTrainedModel",
                   "SSLConfig", "hf_hub_download", "Wav2Vec2ForPreTraining"):
        assert banned not in out, f"{banned} still referenced in vendored file"

    open(DST, "w").write(out)
    print(f"wrote {DST} ({len(out.splitlines())} lines) from {SRC}")


if __name__ == "__main__":
    main()
